
export const countries = [
  { name: "Afghan", code: "AF", flag: "https://flagcdn.com/w320/af.png" },
  { name: "Albanian", code: "AL", flag: "https://flagcdn.com/w320/al.png" },
  { name: "Algerian", code: "DZ", flag: "https://flagcdn.com/w320/dz.png" },
  { name: "American", code: "US", flag: "https://flagcdn.com/w320/us.png" },
  { name: "Andorran", code: "AD", flag: "https://flagcdn.com/w320/ad.png" },
  { name: "Angolan", code: "AO", flag: "https://flagcdn.com/w320/ao.png" },
  { name: "Antiguan", code: "AG", flag: "https://flagcdn.com/w320/ag.png" },
  { name: "Argentine", code: "AR", flag: "https://flagcdn.com/w320/ar.png" },
  { name: "Armenian", code: "AM", flag: "https://flagcdn.com/w320/am.png" },
  { name: "Australian", code: "AU", flag: "https://flagcdn.com/w320/au.png" },
  { name: "Austrian", code: "AT", flag: "https://flagcdn.com/w320/at.png" },
  { name: "Azerbaijani", code: "AZ", flag: "https://flagcdn.com/w320/az.png" },
  { name: "Bahamian", code: "BS", flag: "https://flagcdn.com/w320/bs.png" },
  { name: "Bahraini", code: "BH", flag: "https://flagcdn.com/w320/bh.png" },
  { name: "Bangladeshi", code: "BD", flag: "https://flagcdn.com/w320/bd.png" },
  { name: "Barbadian", code: "BB", flag: "https://flagcdn.com/w320/bb.png" },
  { name: "Belarusian", code: "BY", flag: "https://flagcdn.com/w320/by.png" },
  { name: "Belgian", code: "BE", flag: "https://flagcdn.com/w320/be.png" },
  { name: "Belizean", code: "BZ", flag: "https://flagcdn.com/w320/bz.png" },
  { name: "Beninese", code: "BJ", flag: "https://flagcdn.com/w320/bj.png" },
  { name: "Bhutanese", code: "BT", flag: "https://flagcdn.com/w320/bt.png" },
  { name: "Bolivian", code: "BO", flag: "https://flagcdn.com/w320/bo.png" },
  { name: "Bosnian", code: "BA", flag: "https://flagcdn.com/w320/ba.png" },
  { name: "Botswanan", code: "BW", flag: "https://flagcdn.com/w320/bw.png" },
  { name: "Brazilian", code: "BR", flag: "https://flagcdn.com/w320/br.png" },
  { name: "British", code: "GB", flag: "https://flagcdn.com/w320/gb.png" },
  { name: "Bruneian", code: "BN", flag: "https://flagcdn.com/w320/bn.png" },
  { name: "Bulgarian", code: "BG", flag: "https://flagcdn.com/w320/bg.png" },
  { name: "Burkinabe", code: "BF", flag: "https://flagcdn.com/w320/bf.png" },
  { name: "Burmese (Myanmar)", code: "MM", flag: "https://flagcdn.com/w320/mm.png" },
  { name: "Burundian", code: "BI", flag: "https://flagcdn.com/w320/bi.png" },
  { name: "Cambodian", code: "KH", flag: "https://flagcdn.com/w320/kh.png" },
  { name: "Cameroonian", code: "CM", flag: "https://flagcdn.com/w320/cm.png" },
  { name: "Canadian", code: "CA", flag: "https://flagcdn.com/w320/ca.png" },
  { name: "Cape Verdean", code: "CV", flag: "https://flagcdn.com/w320/cv.png" },
  { name: "Central African", code: "CF", flag: "https://flagcdn.com/w320/cf.png" },
  { name: "Chadian", code: "TD", flag: "https://flagcdn.com/w320/td.png" },
  { name: "Chilean", code: "CL", flag: "https://flagcdn.com/w320/cl.png" },
  { name: "Chinese", code: "CN", flag: "https://flagcdn.com/w320/cn.png" },
  { name: "Colombian", code: "CO", flag: "https://flagcdn.com/w320/co.png" },
  { name: "Comorian", code: "KM", flag: "https://flagcdn.com/w320/km.png" },
  { name: "Congolese (DRC)", code: "CD", flag: "https://flagcdn.com/w320/cd.png" },
  { name: "Congolese (Republic)", code: "CG", flag: "https://flagcdn.com/w320/cg.png" },
  { name: "Costa Rican", code: "CR", flag: "https://flagcdn.com/w320/cr.png" },
  { name: "Croatian", code: "HR", flag: "https://flagcdn.com/w320/hr.png" },
  { name: "Cuban", code: "CU", flag: "https://flagcdn.com/w320/cu.png" },
  { name: "Cypriot", code: "CY", flag: "https://flagcdn.com/w320/cy.png" },
  { name: "Czech", code: "CZ", flag: "https://flagcdn.com/w320/cz.png" },
  { name: "Danish", code: "DK", flag: "https://flagcdn.com/w320/dk.png" },
  { name: "Djiboutian", code: "DJ", flag: "https://flagcdn.com/w320/dj.png" },
  { name: "Dominican", code: "DO", flag: "https://flagcdn.com/w320/do.png" },
  { name: "Dominican Republic", code: "DO", flag: "https://flagcdn.com/w320/do.png" },
  { name: "Dutch", code: "NL", flag: "https://flagcdn.com/w320/nl.png" },
  { name: "East Timorese", code: "TL", flag: "https://flagcdn.com/w320/tl.png" },
  { name: "Ecuadorian", code: "EC", flag: "https://flagcdn.com/w320/ec.png" },
  { name: "Egyptian", code: "EG", flag: "https://flagcdn.com/w320/eg.png" },
  { name: "Emirati", code: "AE", flag: "https://flagcdn.com/w320/ae.png" },
  { name: "English", code: "GB", flag: "https://flagcdn.com/w320/gb.png" },
  { name: "Equatorial Guinean", code: "GQ", flag: "https://flagcdn.com/w320/gq.png" },
  { name: "Eritrean", code: "ER", flag: "https://flagcdn.com/w320/er.png" },
  { name: "Estonian", code: "EE", flag: "https://flagcdn.com/w320/ee.png" },
  { name: "Ethiopian", code: "ET", flag: "https://flagcdn.com/w320/et.png" },
  { name: "Fijian", code: "FJ", flag: "https://flagcdn.com/w320/fj.png" },
  { name: "Filipino", code: "PH", flag: "https://flagcdn.com/w320/ph.png" },
  { name: "Finnish", code: "FI", flag: "https://flagcdn.com/w320/fi.png" },
  { name: "French", code: "FR", flag: "https://flagcdn.com/w320/fr.png" },
  { name: "Gabonese", code: "GA", flag: "https://flagcdn.com/w320/ga.png" },
  { name: "Gambian", code: "GM", flag: "https://flagcdn.com/w320/gm.png" },
  { name: "Georgian", code: "GE", flag: "https://flagcdn.com/w320/ge.png" },
  { name: "German", code: "DE", flag: "https://flagcdn.com/w320/de.png" },
  { name: "Ghanaian", code: "GH", flag: "https://flagcdn.com/w320/gh.png" },
  { name: "Greek", code: "GR", flag: "https://flagcdn.com/w320/gr.png" },
  { name: "Grenadian", code: "GD", flag: "https://flagcdn.com/w320/gd.png" },
  { name: "Guatemalan", code: "GT", flag: "https://flagcdn.com/w320/gt.png" },
  { name: "Guinean", code: "GN", flag: "https://flagcdn.com/w320/gn.png" },
  { name: "Guyanese", code: "GY", flag: "https://flagcdn.com/w320/gy.png" },
  { name: "Haitian", code: "HT", flag: "https://flagcdn.com/w320/ht.png" },
  { name: "Honduran", code: "HN", flag: "https://flagcdn.com/w320/hn.png" },
  { name: "Hungarian", code: "HU", flag: "https://flagcdn.com/w320/hu.png" },
  { name: "Icelandic", code: "IS", flag: "https://flagcdn.com/w320/is.png" },
  { name: "Indian", code: "IN", flag: "https://flagcdn.com/w320/in.png" },
  { name: "Indonesian", code: "ID", flag: "https://flagcdn.com/w320/id.png" },
  { name: "Iranian", code: "IR", flag: "https://flagcdn.com/w320/ir.png" },
  { name: "Iraqi", code: "IQ", flag: "https://flagcdn.com/w320/iq.png" },
  { name: "Irish", code: "IE", flag: "https://flagcdn.com/w320/ie.png" },
  { name: "Israeli", code: "IL", flag: "https://flagcdn.com/w320/il.png" },
  { name: "Italian", code: "IT", flag: "https://flagcdn.com/w320/it.png" },
  { name: "Jamaican", code: "JM", flag: "https://flagcdn.com/w320/jm.png" },
  { name: "Japanese", code: "JP", flag: "https://flagcdn.com/w320/jp.png" },
  { name: "Jordanian", code: "JO", flag: "https://flagcdn.com/w320/jo.png" },
  { name: "Kazakh", code: "KZ", flag: "https://flagcdn.com/w320/kz.png" },
  { name: "Kenyan", code: "KE", flag: "https://flagcdn.com/w320/ke.png" },
  { name: "Kiribati", code: "KI", flag: "https://flagcdn.com/w320/ki.png" },
  { name: "Korean", code: "KR", flag: "https://flagcdn.com/w320/kr.png" },
  { name: "Kosovar", code: "XK", flag: "https://flagcdn.com/w320/xk.png" },
  { name: "Kuwaiti", code: "KW", flag: "https://flagcdn.com/w320/kw.png" },
  { name: "Kyrgyzstani", code: "KG", flag: "https://flagcdn.com/w320/kg.png" },
  { name: "Laotian", code: "LA", flag: "https://flagcdn.com/w320/la.png" },
  { name: "Latvian", code: "LV", flag: "https://flagcdn.com/w320/lv.png" },
  { name: "Lebanese", code: "LB", flag: "https://flagcdn.com/w320/lb.png" },
  { name: "Lesotho", code: "LS", flag: "https://flagcdn.com/w320/ls.png" },
  { name: "Liberian", code: "LR", flag: "https://flagcdn.com/w320/lr.png" },
  { name: "Libyan", code: "LY", flag: "https://flagcdn.com/w320/ly.png" },
  { name: "Liechtenstein", code: "LI", flag: "https://flagcdn.com/w320/li.png" },
  { name: "Lithuanian", code: "LT", flag: "https://flagcdn.com/w320/lt.png" },
  { name: "Luxembourgian", code: "LU", flag: "https://flagcdn.com/w320/lu.png" },
  { name: "Macedonian", code: "MK", flag: "https://flagcdn.com/w320/mk.png" },
  { name: "Malagasy", code: "MG", flag: "https://flagcdn.com/w320/mg.png" },
  { name: "Malawian", code: "MW", flag: "https://flagcdn.com/w320/mw.png" },
  { name: "Malaysian", code: "MY", flag: "https://flagcdn.com/w320/my.png" },
  { name: "Maldivian", code: "MV", flag: "https://flagcdn.com/w320/mv.png" },
  { name: "Malian", code: "ML", flag: "https://flagcdn.com/w320/ml.png" },
  { name: "Malta", code: "MT", flag: "https://flagcdn.com/w320/mt.png" },
  { name: "Marshallese", code: "MH", flag: "https://flagcdn.com/w320/mh.png" },
  { name: "Mauritian", code: "MU", flag: "https://flagcdn.com/w320/mu.png" },
  { name: "Mauritian", code: "MR", flag: "https://flagcdn.com/w320/mr.png" },
  { name: "Mexican", code: "MX", flag: "https://flagcdn.com/w320/mx.png" },
  { name: "Micronesian", code: "FM", flag: "https://flagcdn.com/w320/fm.png" },
  { name: "Moldovan", code: "MD", flag: "https://flagcdn.com/w320/md.png" },
  { name: "Monacan", code: "MC", flag: "https://flagcdn.com/w320/mc.png" },
  { name: "Mongolian", code: "MN", flag: "https://flagcdn.com/w320/mn.png" },
  { name: "Montenegrin", code: "ME", flag: "https://flagcdn.com/w320/me.png" },
  { name: "Moroccan", code: "MA", flag: "https://flagcdn.com/w320/ma.png" },
  { name: "Mozambican", code: "MZ", flag: "https://flagcdn.com/w320/mz.png" },
  { name: "Namibian", code: "NA", flag: "https://flagcdn.com/w320/na.png" },
  { name: "Nauruan", code: "NR", flag: "https://flagcdn.com/w320/nr.png" },
  { name: "Nepali", code: "NP", flag: "https://flagcdn.com/w320/np.png" },
  { name: "New Zealand", code: "NZ", flag: "https://flagcdn.com/w320/nz.png" },
  { name: "Nicaraguan", code: "NI", flag: "https://flagcdn.com/w320/ni.png" },
  { name: "Nigerien", code: "NE", flag: "https://flagcdn.com/w320/ne.png" },
  { name: "Nigerian", code: "NG", flag: "https://flagcdn.com/w320/ng.png" },
  { name: "Nicaraguan", code: "NI", flag: "https://flagcdn.com/w320/ni.png" },
  { name: "Norwegian", code: "NO", flag: "https://flagcdn.com/w320/no.png" },
  { name: "Omani", code: "OM", flag: "https://flagcdn.com/w320/om.png" },
  { name: "Pakistani", code: "PK", flag: "https://flagcdn.com/w320/pk.png" },
  { name: "Palauan", code: "PW", flag: "https://flagcdn.com/w320/pw.png" },
  { name: "Panamanian", code: "PA", flag: "https://flagcdn.com/w320/pa.png" },
  { name: "Papua New Guinean", code: "PG", flag: "https://flagcdn.com/w320/pg.png" },
  { name: "Paraguayan", code: "PY", flag: "https://flagcdn.com/w320/py.png" },
  { name: "Peruvian", code: "PE", flag: "https://flagcdn.com/w320/pe.png" },
  { name: "Polish", code: "PL", flag: "https://flagcdn.com/w320/pl.png" },
  { name: "Portuguese", code: "PT", flag: "https://flagcdn.com/w320/pt.png" },
  { name: "Qatari", code: "QA", flag: "https://flagcdn.com/w320/qa.png" },
  { name: "Romanian", code: "RO", flag: "https://flagcdn.com/w320/ro.png" },
  { name: "Russian", code: "RU", flag: "https://flagcdn.com/w320/ru.png" },
  { name: "Rwandan", code: "RW", flag: "https://flagcdn.com/w320/rw.png" },
  { name: "Saint Kitts and Nevis", code: "KN", flag: "https://flagcdn.com/w320/kn.png" },
  { name: "Saint Lucia", code: "LC", flag: "https://flagcdn.com/w320/lc.png" },
  { name: "Saint Vincent and the Grenadines", code: "VC", flag: "https://flagcdn.com/w320/vc.png" },
  { name: "Samoan", code: "WS", flag: "https://flagcdn.com/w320/ws.png" },
  { name: "San Marinese", code: "SM", flag: "https://flagcdn.com/w320/sm.png" },
  { name: "Sao Tomean", code: "ST", flag: "https://flagcdn.com/w320/st.png" },
  { name: "Saudi", code: "SA", flag: "https://flagcdn.com/w320/sa.png" },
  { name: "Senegalese", code: "SN", flag: "https://flagcdn.com/w320/sn.png" },
  { name: "Serbian", code: "RS", flag: "https://flagcdn.com/w320/rs.png" },
  { name: "Seychellois", code: "SC", flag: "https://flagcdn.com/w320/sc.png" },
  { name: "Sierra Leonean", code: "SL", flag: "https://flagcdn.com/w320/sl.png" },
  { name: "Singaporean", code: "SG", flag: "https://flagcdn.com/w320/sg.png" },
  { name: "Slovak", code: "SK", flag: "https://flagcdn.com/w320/sk.png" },
  { name: "Slovenian", code: "SI", flag: "https://flagcdn.com/w320/si.png" },
  { name: "Solomon Islander", code: "SB", flag: "https://flagcdn.com/w320/sb.png" },
  { name: "Somali", code: "SO", flag: "https://flagcdn.com/w320/so.png" },
  { name: "South African", code: "ZA", flag: "https://flagcdn.com/w320/za.png" },
  { name: "South Sudanese", code: "SS", flag: "https://flagcdn.com/w320/ss.png" },
  { name: "Spanish", code: "ES", flag: "https://flagcdn.com/w320/es.png" },
  { name: "Sri Lankan", code: "LK", flag: "https://flagcdn.com/w320/lk.png" },
  { name: "Sudanese", code: "SD", flag: "https://flagcdn.com/w320/sd.png" },
  { name: "Surinamese", code: "SR", flag: "https://flagcdn.com/w320/sr.png" },
  { name: "Swazi", code: "SZ", flag: "https://flagcdn.com/w320/sz.png" },
  { name: "Swedish", code: "SE", flag: "https://flagcdn.com/w320/se.png" },
  { name: "Swiss", code: "CH", flag: "https://flagcdn.com/w320/ch.png" },
  { name: "Syrian", code: "SY", flag: "https://flagcdn.com/w320/sy.png" },
  { name: "Taiwanese", code: "TW", flag: "https://flagcdn.com/w320/tw.png" },
  { name: "Tajik", code: "TJ", flag: "https://flagcdn.com/w320/tj.png" },
  { name: "Tanzanian", code: "TZ", flag: "https://flagcdn.com/w320/tz.png" },
  { name: "Thai", code: "TH", flag: "https://flagcdn.com/w320/th.png" },
  { name: "Togolese", code: "TG", flag: "https://flagcdn.com/w320/tg.png" },
  { name: "Tongan", code: "TO", flag: "https://flagcdn.com/w320/to.png" },
  { name: "Trinidadian", code: "TT", flag: "https://flagcdn.com/w320/tt.png" },
  { name: "Tunisian", code: "TN", flag: "https://flagcdn.com/w320/tn.png" },
  { name: "Turkish", code: "TR", flag: "https://flagcdn.com/w320/tr.png" },
  { name: "Turkmen", code: "TM", flag: "https://flagcdn.com/w320/tm.png" },
  { name: "Tuvaluan", code: "TV", flag: "https://flagcdn.com/w320/tv.png" },
  { name: "Ugandan", code: "UG", flag: "https://flagcdn.com/w320/ug.png" },
  { name: "Ukrainian", code: "UA", flag: "https://flagcdn.com/w320/ua.png" },
  { name: "Uruguayan", code: "UY", flag: "https://flagcdn.com/w320/uy.png" },
  { name: "Uzbekistani", code: "UZ", flag: "https://flagcdn.com/w320/uz.png" },
  { name: "Vanuatu", code: "VU", flag: "https://flagcdn.com/w320/vu.png" },
  { name: "Vatican", code: "VA", flag: "https://flagcdn.com/w320/va.png" },
  { name: "Venezuelan", code: "VE", flag: "https://flagcdn.com/w320/ve.png" },
  { name: "Vietnamese", code: "VN", flag: "https://flagcdn.com/w320/vn.png" },
  { name: "Yemeni", code: "YE", flag: "https://flagcdn.com/w320/ye.png" },
  { name: "Zambian", code: "ZM", flag: "https://flagcdn.com/w320/zm.png" },
  { name: "Zimbabwean", code: "ZW", flag: "https://flagcdn.com/w320/zw.png" }
];
